Feat fix typeorm with deleted
TriPSs/nestjs-query pull request #99
Opened 2023-02-17 08:06 UTC by hedwiggggg

Working with the QueryService I was kinda suprised that we can't really query for soft-deleted entities. And we are only able to restore soft-deleted entities if we know the ID which is rarely the case. So the soft-delete / restore functionality was pretty useless for us.

With this two commits I've made these two changes:
- Adding `opts?: { withDeleted?: boolean }` to the other QueryService functions and a conditionally call to `.withDeleted()` on the underlying query-builders.
- Refactoring the RelationQueryBuilder to only add a `deletedAt IS NULL` check at the root level and ignore the related entities. This was necessary to implement a resolver for deleted entities. The dataloaders for the relations of the deleted entity always included a inner-join with `deletedAt IS NULL` which resolved in an error. This should't change the behaviour of the current implementation.

2023-02-17 08:35 UTC, TriPSs commented on packages/query-typeorm/src/services/typeorm-query.service.ts
> +    if (opts?.withDeleted) {
The main reason I think this was not here is because the user could also do this them self if needed:
```ts
this.filterQueryBuilder.select(query)
    .withDeleted()
    .getMany() // or .getCount()
```

But we can ofc add it here for a more easier use.

2023-02-17 08:35 UTC, TriPSs commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
Could you explain a bit more why this is? What is the benefit above not doing `qb.withDeleted()`?

2023-02-17 08:35 UTC, TriPSs commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +    qb.withDeleted()
Gotta say, not sure why but doing this always is not yet something I think is a great idea.

2023-02-17 08:43 UTC, hedwiggggg commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
The `qb.withDeleted()` bubbles down to the innerJoins. For example:

```gql
query {
  addressesWithDeleted {
    country {
      id
    }
  }
}
```

Will trigger the DataLoader for the countries, which will create a query like:

```sql
SELECT ...
FROM "countries"
INNER JOIN "addresses" ON ...
WHERE "country"."deletedAt" IS NULL
AND "address"."deletedAt" IS NULL
```

The above changes in combination with the `qb.withDeleted()`, that's always called generate a query like:

```sql
SELECT ...
FROM "countries"
INNER JOIN "addresses" ON ...
WHERE "country"."deletedAt" IS NULL
```

The deletedAt of the addresses is ignored, because it makes no difference on the result, but makes it impossible to query for countries of specific addresses which are deleted.

2023-02-17 08:46 UTC, hedwiggggg commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +    qb.withDeleted()
It won't make a difference, because if the entity is soft-deleteable the `"deletedAt" IS NULL` check will be injected as long as `withDeleted: false` was passed

2023-02-17 08:53 UTC, hedwiggggg commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +    qb.withDeleted()
If the entity is not soft-deleteable the `qb.withDeleted()` will have no impact

2023-02-17 09:01 UTC, TriPSs commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
Just wondering, but is it actually not correct? If `countries` and `addresses` can both be soft deleted and you do not enable the `withDeleted` should it then return `addresses` that are deleted. I think in the case above we will lose the `withDeleted` part for the `addresses`.

We could make even better support for it by adding it also to the `ReadManyMixin` the same way we did for the `ReadOneMixin`, it should properly pass the `withDeleted` of the relation the the relation query service making sure that if you wanted (or not) to fetch deleted `addresses` that query also becomes correct.

2023-02-17 09:26 UTC, hedwiggggg commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
Yes, exactly. That is the point. We don't need the `withDeleted` part for the `addresses` at this point.

I will try to explain it a bit better. I wanted a custom resolver, to search inside the deleted items, so I made this:

```ts
@Query(() => AddressConnection)
async addressesWithDeleted(
  @Args() query: AddressQuery,
): Promise<ConnectionType<Address>> {
  return AddressConnection.createFromPromise(
    (query) => this.service.query(query, { withDeleted: true }),
    query,
    (filter) => this.service.count(filter, { withDeleted: true }),
  );
}
```

This works as long as I don't query for related items, because the generated query from the dataloaders will include a null-check for the address, which is of course deleted. So GraphQL will throw a `cannot return null for not-nullable field exception`.

```gql
# this will work
query {
  addressesWithDeleted {
    nodes {
      id
    }
  }
}
```

```gql
# this won't work
query {
  addressesWithDeleted {
    nodes {
      id

      country {
        # because the address is deleted, the country will be null
        # and the country is not nullable
        id
      }
    }
  }
}
```

I could have tagged the country relation with `{ withDeleted: true }` inside the decorator, but I 1. don't want to search for deleted countries inside deleted addresses. I only want the countries, that belong to the deleted address. 2. don't want to expose the deleted countries by default.


So why don't need the `withDeleted` part for the `addresses`?

As I said, it makes no difference. I query for countries, not addresses, they will be ignored in the query and are only joined to limit the countries result set. And the countries are still null-checked, as long as I don't include { withDeleted: true } in the decorator. Everything works just like before, except that the joined entities can include deleted entities.

I hope I could explain it a bit better now.

2023-02-17 09:30 UTC, hedwiggggg commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
Without the changes the DataLoader will generate a query like this:
```sql
SELECT ...
FROM "countries"
INNER JOIN "addresses" ON ...
WHERE "country"."deletedAt" IS NULL
AND "address"."deletedAt" IS NULL
```
With the changes like this:
```sql
SELECT ...
FROM "countries"
INNER JOIN "addresses" ON ...
WHERE "country"."deletedAt" IS NULL
```

The result-set will be the same, because the countries are still null-checked. But disabling the null-check on the inner-joins will enable to query for countries, that belong to deleted addresses.

2023-02-17 09:33 UTC, hedwiggggg commented on packages/query-typeorm/src/services/typeorm-query.service.ts
> +    if (opts?.withDeleted) {
What's the reason for the `{ withDeleted?: boolean }` inside `getById` and `findById` then, if not for convenience. The user could just as well do this manually 😆.

2023-02-17 09:36 UTC, TriPSs commented on packages/query-typeorm/src/services/typeorm-query.service.ts
> +    if (opts?.withDeleted) {
Haha, true

2023-02-17 09:39 UTC, TriPSs commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
> I could have tagged the country relation with { withDeleted: true } inside the decorator, but I 1. don't want to search for deleted countries inside deleted addresses. I only want the countries, that belong to the deleted address. 2. don't want to expose the deleted countries by default.

It is a normal `@Relation` right? Cause that will only return the match, you will not be able to filter etc on it.

2023-02-17 09:48 UTC, hedwiggggg commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
This makes no difference. If the @Realtion is tagged with `withDelete: true` and I decide to delete the country, it will be still resolved if I query the address. No matter if I query `addresses` or `addressesWithDeleted`. And this is not a behaviour I want.

2023-02-17 09:55 UTC, TriPSs commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
Okay that is weird, as I would only expect the join on countries if there is also a filter on it. Could you maybe share a bit more of the DTO you use?

I'm a bit hesitant with this I have the feeling this change will break at-least one of my own API's, I want to check/test that also and would like to completely understand your use case so we can make sure we get a solution for everyone :)

2023-02-17 10:06 UTC, hedwiggggg commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
There is no join on countries. Only on the addresses.    
Executing this query:

```gql
query {
  addressesWithDeleted {
    id

    country {
      id
      name
      currency
      currencyCourse
      vat
    }
  }
}
```

Will first fetch all the deleted addresses and then fetch the countries for them. The generated query (with my changes) looks like this:

```sql
SELECT
  "country"."id" AS "country_id",
  "country"."created_at" AS "country_created_at",
  "country"."updated_at" AS "country_updated_at",
  "country"."deleted_at" AS "country_deleted_at",
  "country"."name" AS "country_name",
  "country"."currency" AS "country_currency",
  "country"."currency_course" AS "country_currency_course",
  "country"."vat" AS "country_vat",
  "address"."id" AS "country_address_id"

FROM "country" "country"

INNER JOIN "address" "address" 
  ON "address"."country_id" = "country"."id"

WHERE "country"."deleted_at" IS NULL 
  AND "address"."id" IN ($1, $2, $3, $4, $5)

LIMIT 5 

-- PARAMETERS: ["7","12","13","14","15"]
```

Without my changes, the query looks like this:

```sql
SELECT
  "country"."id" AS "country_id",
  "country"."created_at" AS "country_created_at",
  "country"."updated_at" AS "country_updated_at",
  "country"."deleted_at" AS "country_deleted_at",
  "country"."name" AS "country_name",
  "country"."currency" AS "country_currency",
  "country"."currency_course" AS "country_currency_course",
  "country"."vat" AS "country_vat",
  "address"."id" AS "country_address_id"

FROM "country" "country"

INNER JOIN "address" "address" 
  ON "address"."country_id" = "country"."id"

WHERE "country"."deleted_at" IS NULL 
  AND "address"."deleted_at" IS NULL 
  AND "address"."id" IN ($1, $2, $3, $4, $5)

LIMIT 5 

-- PARAMETERS: ["7","12","13","14","15"]
```

And this will of course return no results.

2023-02-17 10:08 UTC, hedwiggggg commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
The DTO's are faily simple:

```typescript
@Entity()
@ObjectType()
@QueryOptions(QueryOptionsConst)
@FilterableRelation('country', () => Country)
export class Address extends intersect(
  WithId,
  WithTimestamps,
  WithSoftDelete,
  WithStatus,
) {
  // ... all the other fields

  @FilterableField(() => Int)
  @Column({ type: 'bigint' })
  @Index()
  countryId!: number;

  @ManyToOne(() => Country, (country) => country.addresses)
  @JoinColumn()
  country!: Country;
}
```

```typescript
@Entity()
@ObjectType()
@QueryOptions(QueryOptionsConst)
@FilterableOffsetConnection('addresses', () => Address)
export class Country extends intersect(WithId, WithTimestamps, WithSoftDelete) {
  // ... all the other fields

  @OneToMany(() => Address, (address) => address.country)
  addresses!: Address[];
}
```

2023-02-17 10:21 UTC, hedwiggggg commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
An alternative suggestion: if you have another approach to the problem that doesn't cause such profound changes. I am open to those as well.

2023-02-17 17:06 UTC, TriPSs commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
@hedwiggggg thanks for all the info! I'm going to check it and also do some tests locally. Hope you don't mind.

2023-02-17 17:09 UTC, TriPSs commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
Small question: You want to show the countries for the deleted addresses but it is ok that the country could be deleted and therefore return `null` right?

2023-02-19 14:26 UTC, TriPSs requested changes
Thanks for everything! I checked it locally with one of my API's and everything keeps working as expected! 

Can you also check the tests / add a test case for this?

2023-02-19 14:26 UTC, TriPSs commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
```suggestion
      qb = qb.andWhere(`${qb.alias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
```

2023-02-19 14:31 UTC, hedwiggggg commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
Hey, thanks for testing this so quickly, I'm glad everything is working as expected!

"Can you also check the tests / add a test case for this?"

Sure, I'll write some tests for it tomorrow.

2023-02-19 21:43 UTC, TriPSs commented
As I was implementing the `withDeleted` support in the look ahead feature I noticed that the `many.withDeleted` or even the `withDeleted` inside the `ReadResolver` are not implemented. Could you check that out to? 

If this is implemented you would no longer need to do the below
```ts
@Query(() => AddressConnection)
async addressesWithDeleted(
  @Args() query: AddressQuery,
): Promise<ConnectionType<Address>> {
  return AddressConnection.createFromPromise(
    (query) => this.service.query(query, { withDeleted: true }),
    query,
    (filter) => this.service.count(filter, { withDeleted: true }),
  );
}
```

But could just do this:
```ts
withDeleted: true,                  // <- not implemented
one: { withDeleted: true },
many: { withDeleted: true }         // <- not implemented
```

After your changes are done I can/will finish the implementation for the `withDeleted` insde the look ahead, I think for that we are going to need to do the whole filtering of the deleted column ourself (same you are now doing for the relations). As currently, if you have `enableLookAhead` and `withDeleted` enabled it is still adding the `IS NULL` to the query for that relation (because the main `FROM` does not have `withDeleted` or does not use soft delete).

2023-02-20 05:46 UTC, hedwiggggg commented
> As I was implementing the `withDeleted` support in the look ahead feature I noticed that the `many.withDeleted` or even the `withDeleted` inside the `ReadResolver` are not implemented. Could you check that out to?
> 
> If this is implemented you would no longer need to do the below
> 
> ```ts
> @Query(() => AddressConnection)
> async addressesWithDeleted(
>   @Args() query: AddressQuery,
> ): Promise<ConnectionType<Address>> {
>   return AddressConnection.createFromPromise(
>     (query) => this.service.query(query, { withDeleted: true }),
>     query,
>     (filter) => this.service.count(filter, { withDeleted: true }),
>   );
> }
> ```
> 
> But could just do this:
> 
> ```ts
> withDeleted: true,                  // <- not implemented
> one: { withDeleted: true },
> many: { withDeleted: true }         // <- not implemented
> ```
> 
> After your changes are done I can/will finish the implementation for the `withDeleted` insde the look ahead, I think for that we are going to need to do the whole filtering of the deleted column ourself (same you are now doing for the relations). As currently, if you have `enableLookAhead` and `withDeleted` enabled it is still adding the `IS NULL` to the query for that relation (because the main `FROM` does not have `withDeleted` or does not use soft delete).

But wouldn't implementing this lead to always returning the deleted items in the generated queries (readOne... / readMany...)? That's one thing I wanted to avoid.

2023-02-20 08:10 UTC, TriPSs commented
> I wanted either a dedicated query for querying the deleted items, or some kind of variable (withDeleted: Boolean = false) in the generated read(One/Many)... queries. And the first option was the easiest to implement 😃.

Aah okay, yea then you can do this :)

2023-02-20 08:26 UTC, hedwiggggg commented
> > I wanted either a dedicated query for querying the deleted items, or some kind of variable (withDeleted: Boolean = false) in the generated read(One/Many)... queries. And the first option was the easiest to implement 😃.
> 
> Aah okay, yea then you can do this :)

I'm a little bit confused on what to do now.

> As I was implementing the withDeleted support in the look ahead feature I noticed that the many.withDeleted or even the withDeleted inside the ReadResolver are not implemented. Could you check that out to?

This is missing functionality, so imho this belongs to a different issue and has nothing to do with the features I implemented in this pull-request.

So only the test is missing (?)

2023-02-20 08:29 UTC, TriPSs commented
> So only the test is missing (?)

Correct!

2023-02-20 13:42 UTC, hedwiggggg commented
> > So only the test is missing (?)
> 
> Correct!

Well, while trying to write some tests, I ran into a bug that I don't really know how to fix. I wanted to extend the existing e2e test and created a custom service for this:

```typescript
import { InjectRepository } from '@nestjs/typeorm'
import { QueryService } from '@ptc-org/nestjs-query-core'
import { TypeOrmQueryService } from '@ptc-org/nestjs-query-typeorm'

import type { Repository } from 'typeorm'

import { TodoItemEntity } from './todo-item.entity'

@QueryService(TodoItemEntity)
export class TodoItemService extends TypeOrmQueryService<TodoItemEntity> {
  constructor(
    @InjectRepository(TodoItemEntity)
    repo: Repository<TodoItemEntity>
  ) {
    super(repo, { useSoftDelete: true })
  }
}
```

I also extended the custom resolver accordingly:

```typescript
import { Args, Field, ID, InputType, Mutation, Query, Resolver } from '@nestjs/graphql'
import { Filter, InjectAssemblerQueryService } from '@ptc-org/nestjs-query-core'
import { ConnectionType, CRUDResolver } from '@ptc-org/nestjs-query-graphql'
import { TypeOrmQueryService } from '@ptc-org/nestjs-query-typeorm'

import { AuthGuard } from '../auth.guard'
import { TodoItemDTO } from './dto/todo-item.dto'
import { TodoItemInputDTO } from './dto/todo-item-input.dto'
import { TodoItemUpdateDTO } from './dto/todo-item-update.dto'
import { TodoItemAssembler } from './todo-item.assembler'
import { TodoItemConnection, TodoItemQuery } from './types'

const guards = [AuthGuard]

@InputType()
export class RestoreOneTodoItemInput {
  @Field(() => ID, {
    nullable: true,
    description: 'The id of the record to restore.'
  })
  id!: number
}

@Resolver(() => TodoItemDTO)
export class TodoItemResolver extends CRUDResolver(TodoItemDTO, {
  CreateDTOClass: TodoItemInputDTO,
  UpdateDTOClass: TodoItemUpdateDTO,
  enableAggregate: true,
  aggregate: { guards },
  create: { guards },
  update: { guards },
  delete: { guards }
}) {
  constructor(
    @InjectAssemblerQueryService(TodoItemAssembler)
    readonly service: TypeOrmQueryService<TodoItemDTO>
  ) {
    super(service)
  }

  // Set the return type to the TodoItemConnection
  @Query(() => TodoItemConnection)
  completedTodoItems(@Args() query: TodoItemQuery): Promise<ConnectionType<TodoItemDTO>> {
    // add the completed filter the user provided filter
    const filter: Filter<TodoItemDTO> = {
      ...query.filter,
      ...{ completed: { is: true } }
    }

    return TodoItemConnection.createFromPromise((q) => this.service.query(q), { ...query, ...{ filter } })
  }

  // Set the return type to the TodoItemConnection
  @Query(() => TodoItemConnection)
  uncompletedTodoItems(@Args() query: TodoItemQuery): Promise<ConnectionType<TodoItemDTO>> {
    // add the completed filter the user provided filter
    const filter: Filter<TodoItemDTO> = {
      ...query.filter,
      ...{ completed: { is: false } }
    }

    return TodoItemConnection.createFromPromise((q) => this.service.query(q), { ...query, ...{ filter } })
  }

  @Query(() => TodoItemConnection)
  async todoItemsWithDeleted(@Args() query: TodoItemQuery): Promise<ConnectionType<TodoItemDTO>> {
    return TodoItemConnection.createFromPromise(
      (q) => this.service.query(q, { withDeleted: true }),
      query,
      (q) => this.service.count(q, { withDeleted: true })
    )
  }

  @Mutation(() => TodoItemDTO)
  restoreOneTodoItem(
    @Args('input', { type: () => RestoreOneTodoItemInput })
    input: RestoreOneTodoItemInput
  ): Promise<TodoItemDTO> {
    return this.service.restoreOne(input.id)
  }
}
```

And adjusted the module:

```typescript
import { Module } from '@nestjs/common'
import { NestjsQueryGraphQLModule } from '@ptc-org/nestjs-query-graphql'
import { NestjsQueryTypeOrmModule } from '@ptc-org/nestjs-query-typeorm'

import { TodoItemDTO } from './dto/todo-item.dto'
import { TodoItemInputDTO } from './dto/todo-item-input.dto'
import { TodoItemUpdateDTO } from './dto/todo-item-update.dto'
import { TodoItemAssembler } from './todo-item.assembler'
import { TodoItemEntity } from './todo-item.entity'
import { TodoItemResolver } from './todo-item.resolver'
import { TodoItemService } from './todo-item.service'

@Module({
  providers: [TodoItemResolver],

  imports: [
    NestjsQueryGraphQLModule.forFeature({
      services: [TodoItemService],
      imports: [NestjsQueryTypeOrmModule.forFeature([TodoItemEntity])],
      assemblers: [TodoItemAssembler],
      dtos: [
        {
          DTOClass: TodoItemDTO,
          CreateDTOClass: TodoItemInputDTO,
          UpdateDTOClass: TodoItemUpdateDTO
        }
      ]
    })
  ]
})
export class TodoItemModule {}
```

Everything compiles and starts as it should. But the curious thing is that in the `AssemblerQueryService` not my `QueryService` is injected, but a generic one that has `{ useSoftDelete: false }`.

And I traced it down to the following behaviour:
- in the module we call `NestjsQueryGraphQLModule.forFeature` and pass the assembler
- in `NestjsQueryGraphQLModule.forFeature` (`/nestjs-query/packages/query-graphql/src/module.ts`) we call `NestjsQueryGraphQLModule.getCoreModule`, which calls `NestjsQueryCoreModule.forFeature` with the assemblers.
- in `NestjsQueryCoreModule.forFeature` (`nestjs-query/packages/core/src/module.ts`) we call `createServices`
- in `createServices` (`nestjs-query/packages/core/src/providers.ts`) we call `createServiceProvider` where we instantiate a new `AssemblerQueryService` with the `getQueryServiceToken(EntityClass)` inject and a factory-function
- the `entityService` then passed to the `AssemblerQueryService` when the factory-function get's called is a generic `TypeOrmQueryService` with `{ useSoftDelete: false }`

The following two things came to mind as I traced the flow.:
1. The `AssemblerQueryService` get's instantiated before my `TodoItemService` is tagged as injectable and registered in nestjs' cache (very unlikely)
2. The injectable of my custom `TodoItemService` get's overridden somewhere from nestjs-query (is this possible?).

2023-02-20 13:50 UTC, TriPSs commented
I think you can just use `@Inject(TodoItemAssembler)` instead of `@InjectAssemblerQueryService(TodoItemAssembler)`

2023-02-21 08:02 UTC, hedwiggggg commented
> I think you can just use `@Inject(TodoItemAssembler)` instead of `@InjectAssemblerQueryService(TodoItemAssembler)`

Thank you, creating the AssemblerQueryService manually with my own service worked perfectly!

2023-02-21 10:14 UTC, TriPSs commented on examples/typeorm/e2e/todo-item.resolver.spec.ts
> +    it(`should return deletedTodos and their subTasks`, async () => {
Maybe it was easier to add these e2e tests inside `examples/typeorm-soft-delete`?

2023-02-21 10:16 UTC, hedwiggggg commented on examples/typeorm/e2e/todo-item.resolver.spec.ts
> +    it(`should return deletedTodos and their subTasks`, async () => {
Yup.. Must have overlooked the folder.

2023-02-21 10:16 UTC, TriPSs commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
Could you check the suggested change? Think that's a bit cleaner, we also use the same above it.

2023-02-21 10:17 UTC, hedwiggggg commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
I should have accepted this change earlier.

2023-02-21 10:19 UTC, TriPSs commented on packages/query-typeorm/src/query/relation-query.builder.ts
> +      qb = qb.andWhere(`${this.relationMeta.fromAlias}.${this.relationRepo.metadata.deleteDateColumn.propertyName} IS NULL`)
Sorry you are right, I clicked on the file link above and that one when't to the old version.

2023-02-22 12:44 UTC, hedwiggggg commented
Test's should no longer fail with the latest commit, could you trigger the pipeline please? @TriPSs

2023-02-23 14:48 UTC, TriPSs approved these changes

2023-03-01 18:00 UTC, merged

2023-03-01 18:06 UTC, TriPSs commented
Massive thanks for the PR! This is now released 🎉